/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orpheusclient;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author ASUS
 */
public class PlayerGUI extends javax.swing.JFrame {

    /**
     * Creates new form PlayerGUI
     */
    int index=0;
    MP3Player p=null;
    Media m;
    MediaPlayer mp;
    private ArrayList<File> files = new ArrayList();
    private static PlayerGUI l= createInstance();
    
    public static PlayerGUI getInstance(){
        return l;
    }
    public void listFiles(){
        files.clear();
        walk("D:/albums");
    }
    private void walk(String path){
        File root = new File(path);
        File[] list = root.listFiles();
        
        if (list == null) return;

        for ( File f : list ) {
            if ( f.isDirectory() ) {
                walk( f.getAbsolutePath() );
               
            }
            else {
                if(f.getName().contains(".mp3")) files.add(f);
            }
        }
    }
    
    private static PlayerGUI createInstance(){
        PlayerGUI l=null;
        try {
            l= new PlayerGUI();
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(l);
            l.pack();
            l.setVisible(true);
            l.setResizable(false);
        
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return l;
        
    }
    
    private PlayerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        songtitle = new javax.swing.JLabel();
        player_play = new javax.swing.JToggleButton();
        player_pause = new javax.swing.JToggleButton();
        player_next = new javax.swing.JToggleButton();
        player_prev = new javax.swing.JToggleButton();
        player_stop = new javax.swing.JToggleButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        songtitle.setText("nama lagu");

        buttonGroup1.add(player_play);
        player_play.setText("play");
        player_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_playActionPerformed(evt);
            }
        });

        buttonGroup1.add(player_pause);
        player_pause.setText("pause");
        player_pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_pauseActionPerformed(evt);
            }
        });

        buttonGroup1.add(player_next);
        player_next.setText("next");
        player_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_nextActionPerformed(evt);
            }
        });

        buttonGroup1.add(player_prev);
        player_prev.setText("prev");
        player_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_prevActionPerformed(evt);
            }
        });

        buttonGroup1.add(player_stop);
        player_stop.setText("stop");
        player_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_stopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(player_play, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player_pause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player_next)
                .addGap(18, 18, 18)
                .addComponent(player_prev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player_stop)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(songtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(songtitle)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player_play)
                    .addComponent(player_pause)
                    .addComponent(player_next)
                    .addComponent(player_prev)
                    .addComponent(player_stop))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void player_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_playActionPerformed
        if (p==null || !p.isAlive()) p= new MP3Player();
        else if (!p.isInterrupted()) {
            p.resume();
            return;
        }
        p.setFile(files.get(index));
        p.start();
        songtitle.setText(files.get(index).getName());
    }//GEN-LAST:event_player_playActionPerformed

    private void player_pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_pauseActionPerformed
        if (p!=null) p.suspend();
    }//GEN-LAST:event_player_pauseActionPerformed

    private void player_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_nextActionPerformed
        index++;
        p.stop();
        p= new MP3Player();
        p.setFile(files.get(index));
        songtitle.setText(files.get(index).getName());
        p.start();
    }//GEN-LAST:event_player_nextActionPerformed

    private void player_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_prevActionPerformed
        index--;
        p.stop();
        p=new MP3Player();
        p.setFile(files.get(index));
        songtitle.setText(files.get(index).getName());
        p.start();
    }//GEN-LAST:event_player_prevActionPerformed

    private void player_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_stopActionPerformed
        p.stop();
    }//GEN-LAST:event_player_stopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlayerGUI p = PlayerGUI.getInstance();
                p.listFiles();
                p.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToggleButton player_next;
    private javax.swing.JToggleButton player_pause;
    private javax.swing.JToggleButton player_play;
    private javax.swing.JToggleButton player_prev;
    private javax.swing.JToggleButton player_stop;
    private javax.swing.JLabel songtitle;
    // End of variables declaration//GEN-END:variables
}
